Update integrationTests.yaml

diff --git a/.github/workflows/integrationTests.yaml b/.github/workflows/integrationTests.yaml
--- a/.github/workflows/integrationTests.yaml
+++ b/.github/workflows/integrationTests.yaml
@@ -10,36 +10,36 @@ env:
 
 jobs:
   integration-tests:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+     runs-on: ubuntu-latest
+     steps:
+       - name: Checkout repository
+         uses: actions/checkout@v4
 
-      - name: Install Bun
-        uses: oven-sh/setup-bun@v2
+  #     - name: Install Bun
+  #       uses: oven-sh/setup-bun@v2
 
-      - name: Install Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: "23"
+  #     - name: Install Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: "23"
 
-      - name: Install required packages
-        run: |
-          sudo apt update
-          sudo apt -y install build-essential pkg-config libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
+  #     - name: Install required packages
+  #       run: |
+  #         sudo apt update
+  #         sudo apt -y install build-essential pkg-config libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
 
-      - name: Install dependencies
-        run: bun install
+  #     - name: Install dependencies
+  #       run: bun install
 
-      - name: Build packages
-        run: bun run build
+  #     - name: Build packages
+  #       run: bun run build
 
-      - name: Check for API key
-        run: |
-          if [ -z "$OPENAI_API_KEY" ]; then
-              echo "Error: OPENAI_API_KEY is not set."
-              exit 1
-          fi
+  #     - name: Check for API key
+  #       run: |
+  #         if [ -z "$OPENAI_API_KEY" ]; then
+  #             echo "Error: OPENAI_API_KEY is not set."
+  #             exit 1
+  #         fi
 
-      - name: Run integration tests
-        run: bun run test
+  #     - name: Run integration tests
+  #       run: bun run test
